# Generated by Django 2.0.2 on 2018-04-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='static/img/users')),
                ('fans', models.ManyToManyField(related_name='star', to='crm.Users')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=False, to='crm.Users'),
        ),
    ]
