# Generated by Django 2.0.2 on 2018-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_users_fans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'QQ群'), (1, '知乎'), (2, '线下广告'), (3, '头条推广')]),
        ),
    ]
