# Generated by Django 2.0.2 on 2018-04-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180426_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='data',
            new_name='date',
        ),
    ]
