# Generated by Django 2.0.2 on 2018-04-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180426_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='cousultant',
            new_name='consultant',
        ),
    ]
