# Generated by Django 2.0.2 on 2018-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20180504_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='custamer',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='contract_agreed',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='contract_approved',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('customer', 'class_grade')},
        ),
    ]
