# Generated by Django 2.0.2 on 2018-05-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180504_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='contract_approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='contract_signed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
