# Generated by Django 2.0.2 on 2018-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_studentenrollment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='enrollment',
            field=models.ForeignKey(on_delete=False, to='crm.StudentEnrollment'),
        ),
    ]
