# Generated by Django 2.0.2 on 2018-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20180505_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='company',
            field=models.CharField(default=2008, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='id_num',
            field=models.IntegerField(default=2008),
            preserve_default=False,
        ),
    ]
