# Generated by Django 2.0.2 on 2018-05-06 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('crm', '0013_auto_20180505_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'verbose_name_plural': '合同'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_list', '可以查看kingadmin每张表里所有的数据'), ('crm_table_list_view', '可以访问kingadmin表里每条数据的修改页'), ('crm_table_list_change', '可以对kingadmin表里的每条数据进行修改'), ('crm_table_obj_add_view', '可以访问kingadmin每张表的数据增加页'), ('crm_table_obj_add', '可以对kingadmin每张表进行数据添加'))},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=2007, max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=2007, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='consult_content',
            field=models.TextField(max_length=500, verbose_name='合作事项'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='consultant',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='商议人（销售）'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='contact',
            field=models.CharField(max_length=200, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='contact_type',
            field=models.SmallIntegerField(choices=[(0, 'QQ'), (1, '微信'), (2, '手机')], verbose_name='联系类型'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='合作日期'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='id_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='source',
            field=models.SmallIntegerField(choices=[(0, '网站宣传'), (1, '高校合作'), (2, '企业合作'), (3, '线下广告')], verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未合作'), (1, '已合作')], verbose_name='合作状态'),
        ),
    ]
