# Generated by Django 2.0.2 on 2018-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20180506_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default=1947, upload_to='static/img/users'),
            preserve_default=False,
        ),
    ]
