# Generated by Django 2.0.2 on 2018-05-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20180506_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
