# Generated by Django 2.0.2 on 2018-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20180506_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(upload_to='static/img/UserProfile'),
        ),
    ]
